# Generated by Django 5.2.5 on 2025-08-13 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_balance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Balance',
        ),
    ]
